project_id = "axnosviewcbhmpzsnpco"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false

[functions.send-inquiry-notification]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.manage-users]
verify_jwt = true
