ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS about_hero_image_path TEXT,
  ADD COLUMN IF NOT EXISTS about_story_image_path TEXT,
  ADD COLUMN IF NOT EXISTS about_portrait_image_path TEXT,
  ADD COLUMN IF NOT EXISTS about_hero_eyebrow TEXT,
  ADD COLUMN IF NOT EXISTS about_hero_title TEXT,
  ADD COLUMN IF NOT EXISTS about_story_label TEXT,
  ADD COLUMN IF NOT EXISTS about_story_heading TEXT,
  ADD COLUMN IF NOT EXISTS about_story_paragraph_1 TEXT,
  ADD COLUMN IF NOT EXISTS about_story_paragraph_2 TEXT,
  ADD COLUMN IF NOT EXISTS about_story_quote TEXT,
  ADD COLUMN IF NOT EXISTS about_story_quote_attribution TEXT,
  ADD COLUMN IF NOT EXISTS about_leader_name TEXT,
  ADD COLUMN IF NOT EXISTS about_leader_role TEXT,
  ADD COLUMN IF NOT EXISTS about_promise_label TEXT,
  ADD COLUMN IF NOT EXISTS about_promise_heading TEXT,
  ADD COLUMN IF NOT EXISTS about_promise_paragraph TEXT,
  ADD COLUMN IF NOT EXISTS about_partners_label TEXT,
  ADD COLUMN IF NOT EXISTS about_partners_heading TEXT,
  ADD COLUMN IF NOT EXISTS about_partners JSONB NOT NULL DEFAULT '[]'::jsonb;