// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-properties.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_properties_default = defineTool({
  name: "list_properties",
  title: "List properties",
  description: "List OCDG properties with optional status filter. Returns slug, title, status, price, published, and has_page.",
  inputSchema: {
    status: z.enum(["active", "under_contract", "coming_soon", "sold"]).optional().describe("Filter by property status."),
    published_only: z.boolean().optional().describe("If true, only return published properties."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, published_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("properties").select("slug,title,status,price,published,has_page,sort_order").order("sort_order", { ascending: true }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (published_only) q = q.eq("published", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { properties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-property.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_property_default = defineTool2({
  name: "get_property",
  title: "Get property",
  description: "Fetch full details of a single OCDG property by slug.",
  inputSchema: {
    slug: z2.string().min(1).describe("Property slug, e.g. 3112-bay-ave.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("properties").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No property with slug "${slug}"` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { property: data }
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool3({
  name: "list_leads",
  title: "List recent leads",
  description: "List recent inquiry leads submitted to OCDG. Admin-only: rows are gated by RLS on the leads table.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows to return (default 25)."),
    interest: z3.string().optional().describe("Filter by lead interest / property slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, interest }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("leads").select("id,created_at,name,email,phone,interest,message,source").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (interest) q = q.eq("interest", interest);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "axnosviewcbhmpzsnpco";
var mcp_default = defineMcp({
  name: "ocdg-admin-mcp",
  title: "Ocean City Development Group",
  version: "0.1.0",
  instructions: "Tools to inspect Ocean City Development Group's property portfolio and inquiry leads. Use `list_properties` to browse the portfolio, `get_property` for full details on one home, and `list_leads` to review recent inquiries (admin only).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_properties_default, get_property_default, list_leads_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
